FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY inferencia.py .
COPY model.h5 .
COPY scaler.pkl .
COPY features.json .

CMD ["python", "inferencia.py"]